### PR TITLE
code refactor

### PR DESCRIPTION
**Pull request by cuihq**
1. change the ruby data file to the yaml data file.
2. autoload the yaml db file under the yaml dir.

### CODE REVIEW

**Comment by mwunsch** [comment]
What's the benefit of this? I'm not sure I see a benefit in defining something in a special serialization format when it's just as readable in executable code.

**Comment by cuihq** [comment]
## More maintainable
* Separate the data files from the source file, no noise
* Separate category by file name, convention than the configured

## More expansible
* Add or change symbol to the data file
* Add or change new function to the source file

## More reusable
* Using the data without the source file, you can do new DSL, if you like,even other language, such nodejs...
* Using the source file without the data file, you can define the symbol in different environment, em.., tick: ✔(windows) and √(linux,Mac)

## More and more
At least do no harm...

**Comment by cuihq** [comment]
1. remove multiple codepoints function
2. 500-times increase in efficiency than the original

**Comment by mwunsch** [comment]
I don't get it. You've now removed a bunch of tests and claim huge gains in efficiency without posting the benchmarks here. You've made a bunch of seemingly minor syntactic changes. And you've extracted the set of items into a YAML document that needs to be parsed into a data structure anyway.

None of these things make much sense to me. We can discuss each one of these changes in a separate PR but none of them appear justified.

**Comment by cuihq** [comment]
None of these things make much sense to you, but me.
* I just want use the rumoji data by nodejs, but nodejs can't use the format of ruby file.
So, I must **maintain** the data files myself. 
* When I coding with nodejs, I'm not sure the multiple codepoints make much sense to me.

But,thanks a lot.:smile:

**Pull request closed without merging**
