### PR TITLE
2014-2015 emojis (http://www.unicode.org/emoji/charts/full-emoji-list.html)

### PR DESCRIPTION
**Pull request by iQuarK**
Support for new emojis.

### CODE REVIEW

**Comment by mwunsch** [comment]
Cool! Thank you!

**Comment by dgilperez** [comment]
Thanks! 

Enough for a new release?

**Comment by mwunsch** [comment]
Probably! Need to get test suite and CI updated onto newer versions of Ruby. Thanks!

**Comment by mikekellyio** [comment]
@mwunsch have you gotten a chance to do the updates you needed before tagging a new release? the speed improvements in master vs 0.4.1 are significant :+1:

**Pull request merged**
